# SPDX-License-Identifier: MIT
---
# Put the tasks for your role here.

# An example of how to set distribution and version specific internal variables
# (defined in vars/ directory):
- name: Set version specific variables
  include_tasks: set_vars.yml

# Examples of some tasks:
- name: Ensure required packages are installed
  package:
    name: "{{ __template_packages }}"
    state: present

- name: Ensure required services are enabled and started
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ __template_services }}"

- name: Generate /etc/{{ __template_foo_config }}
  template:
    src: "{{ __template_foo_config }}.j2"
    dest: /etc/{{ __template_foo_config }}
    backup: yes
  notify: template handler to restart services
