- hosts: all
  vars:
    tox_lsr: "git+https://github.com/linux-system-roles/tox-lsr@main"
  tasks:
    - name: Install requirements
      package:
        name: [python-tox, python-pip, git]

    - name: Install tox-lsr
      pip:
        name: "{{ tox_lsr }}"
