- hosts: all
  vars:
    tox_lsr: "git+https://github.com/linux-system-roles/tox-lsr@main"
  tasks:
    - name: Install requirements
      package:
        name: [python3-tox, python3-pip, git, podman]

    - name: Install tox-lsr
      pip:
        name: "{{ tox_lsr }}"

    - name: Install config file
      get_url:
        url: https://raw.githubusercontent.com/linux-system-roles/linux-system-roles.github.io/master/download/linux-system-roles.json
        dest: /root/.config/linux-system-roles.json
