- hosts: all
  tasks:
    - name: Install requirements
      package:
        name: [git, python3-pip, python3-virtualenv, python3-setuptools]
    - name: ansible 2.9 in venv
      pip:
        name: ansible==2.9.*
        virtualenv: /tmp/.venv
      when:
        - ansible_facts["distribution"] == "CentOS"
        - ansible_facts["distribution_major_version"] | int < 9
    - name: ansible-core 2.13 in venv
      pip:
        name: ansible-core==2.13.*
        virtualenv: /tmp/.venv
      when:
        - ansible_facts["distribution"] == "Fedora"
