# SPDX-License-Identifier: MIT
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint.yml
platforms:
  - name: centos-6
    image: docker.io/linuxsystemroles/centos-6
    privileged: true
  - name: centos-7
    image: registry.centos.org/centos/systemd:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ../../tests/tests_default.yml
scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - check
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
