---
# yamllint disable rule:line-length
name: Convert README.md to HTML and push to docs branch
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - README.md
permissions:
  contents: read
jobs:
  build_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Ensure that the docs directory exist
        run: mkdir -p docs

      - name: Convert README.md to HTML and save to docs/index.html
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --from gfm --to html5 --toc --shift-heading-level-by=-1
            --template https://raw.githubusercontent.com/linux-system-roles/auto-maintenance/47745a818c7c404bd5eb1ba6efb31e1b29c6bef2/GitHub.html5
            --output docs/index.html ref_branch/README.md

      - name: Commit changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs/index.html
          git commit -m "Update docs/index.html
          git push

