---
# yamllint disable rule:line-length
name: Convert README.md to HTML for pushes to main
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - README.md
permissions:
  contents: read
jobs:
  build_docs_latest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure that the directory latest exists
        run: mkdir latest

      - name: Convert README.md to HTML and save to the directory latest
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --from gfm --to html5 --toc --shift-heading-level-by=-1
            --template https://raw.githubusercontent.com/linux-system-roles/auto-maintenance/47745a818c7c404bd5eb1ba6efb31e1b29c6bef2/GitHub.html5
            --output latest/README.html README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add latest/README.html
          git commit -m "Update README.html in latest"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs

