# yamllint disable rule:line-length
name: Find Ansible Plugins
on:  # yamllint disable-line rule:truthy
  - pull_request
jobs:
  find-ansible-plugins:
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install ansible, jinja2
        run: |
          set -euxo pipefail
          pip install "ansible==4.*" "jinja2==2.7.*"
          curl -L -o report-modules-plugins.py https://raw.githubusercontent.com/richm/auto-maintenance/report-modules-plugins/report-modules-plugins.py
      - name: Scan Ansible code
        run: |
          set -euo pipefail
          #env
          check_suite_url=$(gh api "/repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" | jq -r '.check_suite_url')
          check_run_id=$(gh api "$check_suite_url/check-runs" | jq '.check_runs[] | select(.name=="find-ansible-plugins") | .id ')
          #gh api "/repos/${GITHUB_REPOSITORY}/check-runs/${check_run_id}" | jq .
          gh api -X PATCH "/repos/${GITHUB_REPOSITORY}/check-runs/${check_run_id}/annotations" -F @- <<EOF
          {
            "output": {
              "title": "This is the title",
              "summary": "This is the summary",
              "text": "This is the text",
              "annotations": [
                {
                  "path": "tasks/main.yml",
                  "start_line": 30,
                  "end_line": 31,
                  "annotation_level": "warning",
                  "message": "This is the message"
                }
              ]
            }
          }
          EOF
          python report-modules-plugins.py $(pwd)
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
