name: Append PR number to commits titles
on:  # yamllint disable-line rule:truthy
  pull_request:
  merge_group:
permissions:
  contents: read
jobs:
  commit-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print the GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      # - name: Get a pull request
      #   id: myRequest
      #   uses: fjogeleit/http-request-action@v1
      #   with:
      #     url: 'https://api.github.com/repos/linux-system-roles/ci-testing/pulls/${{ github.event.number }}/commits'
      #     method: 'GET'
      #     contentType: application/vnd.github+json
      #     bearerToken: ${{ secrets.GITHUB_TOKEN }}
      #     customHeaders: '{"X-GitHub-Api-Version": "2022-11-28"}'

      # - name: Show Response 2
      #   env:
      #     GITHUB_CONTEXT: ${{ steps.myRequest.outputs.response }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Append PR title to commits
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: >-
          git -c sequence.editor=:
          -c user.name=${{ github.event.pull_request.user.login }}
          -c user.email=${{ github.event.pull_request.head.user.email }}
          rebase -i origin/main -x 'sh .pr_num_to_commit.sh' &&
          git log -2 &&
          git remote -v &&
          git status

      - name: Force push rebased commits to the merging branch
        run: echo git push origin ${{ github.head_ref }} --force
        # uses: ad-m/github-push-action@master
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   branch: ${{ github.head_ref }}
        #   force: true
