---
# yamllint disable rule:line-length
name: Convert README.md to HTML and push to main
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - README.md
permissions:
  contents: read
jobs:
  tag_release_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update git
        run: |
          set -euxo pipefail
          sudo apt install -y git

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert README.md to HTML
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --from gfm --to html5 --toc --shift-heading-level-by=-1
            --template https://raw.githubusercontent.com/linux-system-roles/auto-maintenance/47745a818c7c404bd5eb1ba6efb31e1b29c6bef2/GitHub.html5
            --output README.html README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git pull origin main --force
          git add -A
          git commit -m "Update README.html"
          git push
