---
# yamllint disable rule:line-length
name: Test converting README.md to README.html
on:  # yamllint disable-line rule:truthy
  pull_request:
permissions:
  contents: read
jobs:
  convert_readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the workflow branch
        uses: actions/checkout@v3

      - name: Convert README.md to HTML and save to the version directory
        uses: docker://pandoc/core:latest
        with:
          args: >-
            --from gfm --to html5 --toc --shift-heading-level-by=-1
            --template .GitHub_pandoc_template.html5
            --output README.html README.md

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: README.html
          path: README.html
