name: Schedule test on Testing Farm
on:
  issue_comment:
    types:
      - created

jobs:
  tests:
    runs-on: ubuntu-20.04
    # Let's schedule tests only on user request. NOT automatically.
    # Only repository owner or member can schedule tests
    # if: |
    #   github.event.issue.pull_request
    #   && contains(github.event.comment.body, '[test]')
    #   && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - name: Install mandatory packages
        run: |
          sudo apt update && sudo apt -y install curl jq
        shell: bash

      - name: dump github event
        run: |
          echo "${{ github.event.issue.pull_request }}" || :
          echo "${{ github.event.comment.body }}" || :
          echo "${{ github.event.comment.author_association }}" || :

      - name: Checkout repo and switch to corresponding pull request
        uses: actions/checkout@v2
        with:
          git_ref: "refs/pull/${{ github.event.issue.number }}/head"

      - name: Schedule test on Testing Farm
        uses: sclorg/testing-farm-as-github-action@v1
        with:
          api_key: ${{ secrets.TF_API_KEY }}
          git_url: https://github.com/sclorg/sclorg-testing-farm
          tmt_plan_regex: "centos"
          pull_request_status_name: "CentOS 7"
