name: test with tox
on:  # yamllint disable-line rule:truthy
  - pull_request
jobs:
  runtox:
    runs-on: ubuntu-latest
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install platform dependencies
        run: |
          set -euxo pipefail
          bash -x .travis/preinstall
      - name: Install pip, tox, python dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox tests
        run: |
          set -euxo pipefail
          bash -x .travis/runtox
        env:
          LSR_ANSIBLES: 'ansible==2.7.* ansible==2.8.* ansible==2.9.*'
          LSR_MSCENARIOS: default
