name: test with tox
on:  # yamllint disable-line rule:truthy
  - pull_request
jobs:
  runtox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ['2.7', '3.6', '3.7', '3.8', '3.9']
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install platform dependencies
        run: |
          set -euxo pipefail
          .travis/preinstall
      - name: Install pip, tox, python dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox tests
        run: |
          set -euxo pipefail
          .travis/runtox
        env:
          LSR_ANSIBLES: 'ansible==2.7.* ansible==2.8.* ansible==2.9.*'
          LSR_MSCENARIOS: default
  runtox-py26:
    runs-on: ubuntu-14.04
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: check python version
        run: python --version
      - name: Install platform dependencies
        run: |
          set -euxo pipefail
          .travis/preinstall
      - name: Install pip, tox, python dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox tests
        run: |
          set -euxo pipefail
          .travis/runtox
        env:
          LSR_ANSIBLES: 'ansible==2.7.* ansible==2.8.* ansible==2.9.*'
          LSR_MSCENARIOS: default
