name: test with tox
on:  # yamllint disable-line rule:truthy
  - pull_request
jobs:
  runtox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pyver: ['2.7', '3.6', '3.7', '3.8', '3.9']
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyver }}
      - name: Install platform dependencies
        run: |
          set -euxo pipefail
          .travis/preinstall
      - name: Install pip, tox, python dependencies
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tox tests
        run: |
          set -euxo pipefail
          .travis/runtox
        env:
          LSR_ANSIBLES: 'ansible==2.7.* ansible==2.8.* ansible==2.9.*'
          LSR_MSCENARIOS: default
  runtox-py26:
    runs-on: ubuntu-16.04
    steps:
      - name: checkout PR
        uses: actions/checkout@v2
      - name: Install platform dependencies
        run: |
          set -euo pipefail
          curl -sSf --retry 5 -o python-2.6.tar.bz2 ${PY26URL}
          sudo tar xjf python-2.6.tar.bz2 --directory /
          .travis/preinstall
        env:
          # yamllint disable-line rule:line-length
          PY26URL: https://storage.googleapis.com/travis-ci-language-archives/python/binaries/ubuntu/14.04/x86_64/python-2.6.tar.bz2
      - name: Install pip, tox, python dependencies
        run: |
          set -euo pipefail
          source /home/travis/virtualenv/python2.6/bin/activate
          set -x
          sudo pip install tox
        env:
          VIRTUAL_ENV_DISABLE_PROMPT: "true"
      - name: Run tox tests
        run: |
          set -euo pipefail
          source /home/travis/virtualenv/python2.6/bin/activate
          set -x
          .travis/runtox
        env:
          LSR_ANSIBLES: 'ansible==2.7.* ansible==2.8.* ansible==2.9.*'
          LSR_MSCENARIOS: default
          VIRTUAL_ENV_DISABLE_PROMPT: "true"
